'use client'

import { useMemo, useState } from 'react'
import { createClient } from '@supabase/supabase-js'
import { Bell, CircleDollarSign, Gavel, LayoutDashboard, LogOut, Save, Search, Settings, ShoppingBag, Users, Eye, Boxes } from 'lucide-react'

const inventory = [
  { id: 'CC-1048', title: '1986 Fleer Basketball Wax Pack', category: 'Trading Cards', price: '$1,250', status: 'Published', stock: 3 },
  { id: 'CC-1047', title: 'Cat-eye Marble Collection', category: 'Collectibles', price: '$68', status: 'Draft', stock: 8 },
  { id: 'CC-1046', title: 'Sony Walkman WM-2', category: 'Electronics', price: '$340', status: 'Published', stock: 1 },
  { id: 'CC-1045', title: 'Carolina Coastal Postcard Album', category: 'Paper & Postal', price: '$145', status: 'Low stock', stock: 2 },
]

const nav = [{ label: 'Overview', icon: LayoutDashboard }, { label: 'Inventory', icon: Boxes }, { label: 'Orders', icon: ShoppingBag }, { label: 'Auctions', icon: Gavel }, { label: 'Customers', icon: Users }, { label: 'Site Content', icon: Settings }]
const initialSettings = { hero_headline: 'Rare finds. Real stories.', hero_subtitle: 'A curated archive of collectibles, vintage objects, and electronic time capsules.', announcement_text: 'Insured promotional shipping applied at checkout · VIP rewards for returning collectors', about_text: 'Carolina Cache is a small, sharp-eyed archive for the objects that deserve a second look.', footer_contact: 'hello@carolinacache.com · Charlotte, North Carolina', footer_disclaimer: 'Every item is inspected and described with care. Availability and condition may vary.' }

type SettingsState = typeof initialSettings

function getSupabase() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
  return url && key ? createClient(url, key) : null
}

export function AdminDashboard() {
  const [active, setActive] = useState('Overview')
  const [query, setQuery] = useState('')
  const [settings, setSettings] = useState<SettingsState>(initialSettings)
  const [saved, setSaved] = useState(false)
  const [error, setError] = useState('')
  const filtered = useMemo(() => inventory.filter((item) => `${item.title} ${item.category}`.toLowerCase().includes(query.toLowerCase())), [query])
  const update = (key: keyof SettingsState, value: string) => { setSaved(false); setSettings((current) => ({ ...current, [key]: value })) }

  async function saveSettings() {
    setError('')
    const supabase = getSupabase()
    if (!supabase) { setSaved(true); return }
    const { error: saveError } = await supabase.from('site_settings').upsert(Object.entries(settings).map(([key, value]) => ({ key, value })), { onConflict: 'key' })
    if (saveError) setError('Settings could not be saved. Confirm the site_settings table and permissions are configured.')
    else setSaved(true)
  }

  return <div className="min-h-screen bg-[#f4f4f1] text-zinc-950 lg:flex">
    <aside className="hidden w-64 shrink-0 flex-col bg-zinc-950 px-5 py-6 text-white lg:flex"><div className="flex items-center gap-3 border-b border-white/10 pb-7"><div className="grid size-9 place-items-center bg-emerald-400 font-black text-zinc-950">CC</div><div><p className="font-bold">Carolina Cache</p><p className="text-[10px] uppercase tracking-widest text-zinc-500">Admin studio</p></div></div><nav className="mt-8 space-y-1">{nav.map(({ label, icon: Icon }) => <button key={label} onClick={() => setActive(label)} className={`flex w-full items-center gap-3 px-3 py-3 text-left text-sm transition ${active === label ? 'bg-emerald-400 font-bold text-zinc-950' : 'text-zinc-400 hover:bg-white/5 hover:text-white'}`}><Icon className="size-4" />{label}</button>)}</nav><button className="mt-auto flex w-full items-center gap-3 border-t border-white/10 px-3 pt-5 text-sm text-zinc-400 hover:text-white"><LogOut className="size-4" />Sign out</button></aside>
    <main className="min-w-0 flex-1"><header className="flex items-center justify-between border-b border-zinc-200 bg-white px-5 py-4 sm:px-8"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-emerald-700">Workspace / {active}</p><h1 className="mt-1 text-2xl font-black tracking-tight sm:text-3xl">{active === 'Overview' ? 'Good morning, Alex.' : active}</h1></div><div className="flex items-center gap-3"><button aria-label="Notifications" className="relative grid size-10 place-items-center border border-zinc-200"><Bell className="size-4" /></button><div className="hidden items-center gap-2 border-l border-zinc-200 pl-3 sm:flex"><div className="grid size-8 place-items-center rounded-full bg-zinc-950 text-xs font-bold text-white">AS</div><div><p className="text-xs font-bold">Alex Stone</p><p className="text-[10px] text-zinc-500">Owner</p></div></div></div></header><div className="border-b border-zinc-200 bg-white px-5 py-3 lg:hidden"><div className="flex gap-2 overflow-x-auto">{nav.map(({ label, icon: Icon }) => <button key={label} onClick={() => setActive(label)} className={`flex shrink-0 items-center gap-2 px-3 py-2 text-xs font-bold ${active === label ? 'bg-zinc-950 text-white' : 'bg-zinc-100 text-zinc-600'}`}><Icon className="size-3.5" />{label}</button>)}</div></div>
      {active === 'Site Content' ? <ContentSettings settings={settings} update={update} save={saveSettings} saved={saved} error={error} /> : <DashboardOverview active={active} query={query} setQuery={setQuery} filtered={filtered} />}
    </main></div>
}

function ContentSettings({ settings, update, save, saved, error }: { settings: SettingsState; update: (key: keyof SettingsState, value: string) => void; save: () => void; saved: boolean; error: string }) { return <div className="p-5 sm:p-8"><div className="flex flex-col justify-between gap-4 border-b border-zinc-200 pb-6 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-700">Site-wide copy</p><h2 className="mt-2 text-3xl font-black tracking-tight">Text settings</h2><p className="mt-2 max-w-xl text-sm text-zinc-500">Edit the words your collectors see across the storefront. Changes save to the `site_settings` key-value table when Supabase is connected.</p></div><button onClick={save} className="inline-flex items-center justify-center gap-2 bg-zinc-950 px-5 py-3 text-xs font-black uppercase tracking-widest text-white hover:bg-emerald-600"><Save className="size-4" />{saved ? 'Saved' : 'Save changes'}</button></div>{error && <p role="alert" className="mt-5 border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-8 grid gap-6 xl:grid-cols-[1fr_0.85fr]"><div className="space-y-5">{(['hero_headline', 'hero_subtitle', 'announcement_text', 'about_text', 'footer_contact', 'footer_disclaimer'] as const).map((key) => <label key={key} className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-zinc-600">{key.replaceAll('_', ' ')}</span><textarea value={settings[key]} onChange={(event) => update(key, event.target.value)} rows={key.includes('subtitle') || key.includes('about') || key.includes('disclaimer') ? 4 : 2} className="w-full resize-y border border-zinc-300 bg-white px-4 py-3 text-sm outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100" /></label>)}</div><Preview settings={settings} /></div></div> }

function Preview({ settings }: { settings: SettingsState }) { return <aside className="h-fit border border-zinc-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-zinc-500"><Eye className="size-4 text-emerald-600" />Live preview</div><div className="mt-5 overflow-hidden border border-zinc-200"><div className="bg-zinc-950 p-6 text-white"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-emerald-400">Carolina Cache</p><h3 className="mt-5 text-3xl font-black leading-none tracking-tight">{settings.hero_headline || 'Your headline'}</h3><p className="mt-4 text-sm leading-relaxed text-zinc-300">{settings.hero_subtitle || 'Your subtitle'}</p></div><div className="bg-emerald-400 px-4 py-3 text-center text-xs font-bold text-zinc-950">{settings.announcement_text || 'Your announcement'}</div><div className="p-5"><p className="text-[10px] font-bold uppercase tracking-widest text-emerald-700">About Carolina Cache</p><p className="mt-3 text-sm leading-relaxed text-zinc-600">{settings.about_text || 'Your about text'}</p></div><div className="border-t border-zinc-200 bg-zinc-50 p-5 text-xs text-zinc-500"><p className="font-bold text-zinc-800">{settings.footer_contact || 'Contact information'}</p><p className="mt-2 leading-relaxed">{settings.footer_disclaimer || 'Footer disclaimer'}</p></div></div></aside> }

function DashboardOverview({ active, query, setQuery, filtered }: { active: string; query: string; setQuery: (value: string) => void; filtered: typeof inventory }) { return <div className="p-5 sm:p-8"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={CircleDollarSign} label="Gross revenue" value="$24,680" change="+18.4%" /><Stat icon={ShoppingBag} label="Orders" value="186" change="+12.6%" /><Stat icon={Users} label="Customers" value="1,284" change="+8.1%" /><Stat icon={Gavel} label="Live bids" value="42" change="+24.2%" /></section><section className="mt-8 border border-zinc-200 bg-white"><div className="flex flex-col justify-between gap-4 border-b border-zinc-200 p-5 sm:flex-row sm:items-center"><div><h2 className="font-bold">{active} workspace</h2><p className="mt-1 text-xs text-zinc-500">Monitor your Carolina Cache operations.</p></div><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-zinc-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search inventory" className="w-full border border-zinc-200 py-2 pl-9 pr-3 text-sm outline-none focus:border-emerald-500 sm:w-64" /></div></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-zinc-50 text-[10px] uppercase tracking-widest text-zinc-500"><tr><th className="px-5 py-3">Item</th><th className="px-5 py-3">Category</th><th className="px-5 py-3">Price</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Stock</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id} className="border-t border-zinc-100"><td className="px-5 py-4 font-bold">{item.title}<span className="ml-2 text-xs font-normal text-zinc-400">{item.id}</span></td><td className="px-5 py-4 text-zinc-500">{item.category}</td><td className="px-5 py-4 font-bold">{item.price}</td><td className="px-5 py-4"><span className="bg-emerald-50 px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-emerald-700">{item.status}</span></td><td className="px-5 py-4 text-zinc-500">{item.stock}</td></tr>)}</tbody></table></div></section></div> }
function Stat({ icon: Icon, label, value, change }: { icon: typeof CircleDollarSign; label: string; value: string; change: string }) { return <div className="border border-zinc-200 bg-white p-5"><div className="flex items-start justify-between"><div className="grid size-9 place-items-center bg-emerald-100 text-emerald-800"><Icon className="size-4" /></div><span className="text-[10px] font-bold text-emerald-700">{change}</span></div><p className="mt-5 text-xs text-zinc-500">{label}</p><p className="mt-1 text-2xl font-black tracking-tight">{value}</p></div> }
